namespace iRLeagueDatabase.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RevertUserIdentityLeagueUser : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.SeasonEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SeasonEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoringEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoringEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScheduleEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScheduleEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SessionBaseEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SessionBaseEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.CommentBaseEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.CommentBaseEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ResultEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ResultEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoredResultEntities", "CreatedByUserId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoredResultEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities");
            DropIndex("dbo.SeasonEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.SeasonEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.ScoringEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.ScoringEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.ScheduleEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.ScheduleEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.CommentBaseEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.CommentBaseEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.ResultEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.ResultEntities", new[] { "LastModifiedByUserId" });
            DropIndex("dbo.ScoredResultEntities", new[] { "CreatedByUserId" });
            DropIndex("dbo.ScoredResultEntities", new[] { "LastModifiedByUserId" });
            RenameColumn(table: "dbo.SeasonEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.SeasonEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.ScoringEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.ScoringEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.ScheduleEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.ScheduleEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.SessionBaseEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.SessionBaseEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.IncidentReviewEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.IncidentReviewEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.CommentBaseEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.CommentBaseEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.ResultEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.ResultEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            RenameColumn(table: "dbo.ScoredResultEntities", name: "CreatedByUserId", newName: "CreatedBy_MemberId");
            RenameColumn(table: "dbo.ScoredResultEntities", name: "LastModifiedByUserId", newName: "LastModifiedBy_MemberId");
            AddColumn("dbo.IncidentReviewEntities", "AuthorUserId", c => c.String());
            AddColumn("dbo.CommentBaseEntities", "AuthorUserId", c => c.String());
            AlterColumn("dbo.SeasonEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.SeasonEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScoringEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScoringEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScheduleEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScheduleEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.SessionBaseEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.IncidentReviewEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.CommentBaseEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.CommentBaseEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ResultEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ResultEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScoredResultEntities", "CreatedBy_MemberId", c => c.Long(nullable: true));
            AlterColumn("dbo.ScoredResultEntities", "LastModifiedBy_MemberId", c => c.Long(nullable: true));
            CreateIndex("dbo.SeasonEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.SeasonEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScheduleEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScheduleEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.CommentBaseEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.CommentBaseEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ResultEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ResultEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScoredResultEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScoredResultEntities", "LastModifiedBy_MemberId");
            AddForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.CommentBaseEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.CommentBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScoredResultEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
            AddForeignKey("dbo.ScoredResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities", "AdminId", cascadeDelete: false);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ScoredResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoredResultEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.CommentBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.CommentBaseEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueUserEntities");
            DropForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueUserEntities");
            DropIndex("dbo.ScoredResultEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScoredResultEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ResultEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ResultEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.CommentBaseEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.CommentBaseEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScheduleEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScheduleEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.SeasonEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SeasonEntities", new[] { "CreatedBy_MemberId" });
            AlterColumn("dbo.ScoredResultEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScoredResultEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ResultEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ResultEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.CommentBaseEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.CommentBaseEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScheduleEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScheduleEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScoringEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScoringEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SeasonEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SeasonEntities", "CreatedBy_MemberId", c => c.Long());
            DropColumn("dbo.CommentBaseEntities", "AuthorUserId");
            DropColumn("dbo.IncidentReviewEntities", "AuthorUserId");
            RenameColumn(table: "dbo.ScoredResultEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.ScoredResultEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.ResultEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.ResultEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.CommentBaseEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.CommentBaseEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.IncidentReviewEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.IncidentReviewEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.SessionBaseEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.SessionBaseEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.ScheduleEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.ScheduleEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.ScoringEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.ScoringEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            RenameColumn(table: "dbo.SeasonEntities", name: "LastModifiedBy_MemberId", newName: "LastModifiedByUserId");
            RenameColumn(table: "dbo.SeasonEntities", name: "CreatedBy_MemberId", newName: "CreatedByUserId");
            CreateIndex("dbo.ScoredResultEntities", "LastModifiedByUserId");
            CreateIndex("dbo.ScoredResultEntities", "CreatedByUserId");
            CreateIndex("dbo.ResultEntities", "LastModifiedByUserId");
            CreateIndex("dbo.ResultEntities", "CreatedByUserId");
            CreateIndex("dbo.CommentBaseEntities", "LastModifiedByUserId");
            CreateIndex("dbo.CommentBaseEntities", "CreatedByUserId");
            CreateIndex("dbo.IncidentReviewEntities", "LastModifiedByUserId");
            CreateIndex("dbo.IncidentReviewEntities", "CreatedByUserId");
            CreateIndex("dbo.SessionBaseEntities", "LastModifiedByUserId");
            CreateIndex("dbo.SessionBaseEntities", "CreatedByUserId");
            CreateIndex("dbo.ScheduleEntities", "LastModifiedByUserId");
            CreateIndex("dbo.ScheduleEntities", "CreatedByUserId");
            CreateIndex("dbo.ScoringEntities", "LastModifiedByUserId");
            CreateIndex("dbo.ScoringEntities", "CreatedByUserId");
            CreateIndex("dbo.SeasonEntities", "LastModifiedByUserId");
            CreateIndex("dbo.SeasonEntities", "CreatedByUserId");
            AddForeignKey("dbo.ScoredResultEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ScoredResultEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ResultEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ResultEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.CommentBaseEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.CommentBaseEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.IncidentReviewEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.IncidentReviewEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.SessionBaseEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.SessionBaseEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ScheduleEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ScheduleEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ScoringEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.ScoringEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.SeasonEntities", "LastModifiedByUserId", "dbo.LeagueUserEntities", "AdminId");
            AddForeignKey("dbo.SeasonEntities", "CreatedByUserId", "dbo.LeagueUserEntities", "AdminId");
        }
    }
}
