namespace iRLeagueDatabase.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangeKeyType : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultRowEntities", "Member_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "Author_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "Author_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReview_LeagueMember", "MemberRefId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScoringEntities", "SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.ScheduleEntities", "Season_SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.ScoringEntities", "SeasonEntity_SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.MultiScoringMap", "ScoringParentId", "dbo.ScoringEntities");
            DropForeignKey("dbo.MultiScoringMap", "ScoringChildId", "dbo.ScoringEntities");
            DropForeignKey("dbo.Scoring_Session", "ScoringRefId", "dbo.ScoringEntities");
            DropForeignKey("dbo.SeasonEntities", "MainScoring_ScoringId", "dbo.ScoringEntities");
            DropForeignKey("dbo.ResultEntities", "ResultId", "dbo.SessionBaseEntities");
            DropForeignKey("dbo.Scoring_Session", "SessionRefId", "dbo.SessionBaseEntities");
            DropForeignKey("dbo.SessionBaseEntities", "Schedule_ScheduleId", "dbo.ScheduleEntities");
            DropForeignKey("dbo.ResultRowEntities", "ResultId", "dbo.ResultEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "Result_ResultId", "dbo.ResultEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "ReviewId", "dbo.IncidentReviewEntities");
            DropForeignKey("dbo.IncidentReview_LeagueMember", "ReviewRefId", "dbo.IncidentReviewEntities");
            DropIndex("dbo.SeasonEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.SeasonEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SeasonEntities", new[] { "MainScoring_ScoringId" });
            DropIndex("dbo.ScoringEntities", new[] { "SeasonId" });
            DropIndex("dbo.ScoringEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "SeasonEntity_SeasonId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "Schedule_ScheduleId" });
            DropIndex("dbo.ScheduleEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScheduleEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScheduleEntities", new[] { "Season_SeasonId" });
            DropIndex("dbo.ResultEntities", new[] { "ResultId" });
            DropIndex("dbo.ResultEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ResultEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ResultRowEntities", new[] { "ResultId" });
            DropIndex("dbo.ResultRowEntities", new[] { "Member_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "Author_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "MemberAtFault_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "Result_ResultId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "ReviewId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "Author_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "MemberAtFault_MemberId" });
            DropIndex("dbo.MultiScoringMap", new[] { "ScoringParentId" });
            DropIndex("dbo.MultiScoringMap", new[] { "ScoringChildId" });
            DropIndex("dbo.IncidentReview_LeagueMember", new[] { "ReviewRefId" });
            DropIndex("dbo.IncidentReview_LeagueMember", new[] { "MemberRefId" });
            DropIndex("dbo.Scoring_Session", new[] { "ScoringRefId" });
            DropIndex("dbo.Scoring_Session", new[] { "SessionRefId" });
            DropPrimaryKey("dbo.LeagueMemberEntities");
            DropPrimaryKey("dbo.SeasonEntities");
            DropPrimaryKey("dbo.ScoringEntities");
            DropPrimaryKey("dbo.SessionBaseEntities");
            DropPrimaryKey("dbo.ScheduleEntities");
            DropPrimaryKey("dbo.ResultEntities");
            DropPrimaryKey("dbo.ResultRowEntities");
            DropPrimaryKey("dbo.IncidentReviewEntities");
            DropPrimaryKey("dbo.ReviewCommentEntities");
            DropPrimaryKey("dbo.MultiScoringMap");
            DropPrimaryKey("dbo.Scoring_Session");
            DropPrimaryKey("dbo.IncidentReview_LeagueMember");
            AlterColumn("dbo.LeagueMemberEntities", "MemberId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.SeasonEntities", "SeasonId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.SeasonEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SeasonEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SeasonEntities", "MainScoring_ScoringId", c => c.Long());
            AlterColumn("dbo.ScoringEntities", "ScoringId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ScoringEntities", "SeasonId", c => c.Long(nullable: false));
            AlterColumn("dbo.ScoringEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScoringEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScoringEntities", "SeasonEntity_SeasonId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "SessionId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.SessionBaseEntities", "RaceId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.SessionBaseEntities", "Schedule_ScheduleId", c => c.Long(nullable: false));
            AlterColumn("dbo.ScheduleEntities", "ScheduleId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ScheduleEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScheduleEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ScheduleEntities", "Season_SeasonId", c => c.Long(nullable: false));
            AlterColumn("dbo.ResultEntities", "ResultId", c => c.Long(nullable: false));
            AlterColumn("dbo.ResultEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ResultEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ResultRowEntities", "ResultRowId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ResultRowEntities", "ResultId", c => c.Long(nullable: false));
            AlterColumn("dbo.ResultRowEntities", "Member_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "ReviewId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.IncidentReviewEntities", "Author_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", c => c.Long());
            AlterColumn("dbo.IncidentReviewEntities", "Result_ResultId", c => c.Long(nullable: false));
            AlterColumn("dbo.ReviewCommentEntities", "CommentId", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ReviewCommentEntities", "ReviewId", c => c.Long());
            AlterColumn("dbo.ReviewCommentEntities", "Author_MemberId", c => c.Long());
            AlterColumn("dbo.ReviewCommentEntities", "CreatedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", c => c.Long());
            AlterColumn("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", c => c.Long());
            AlterColumn("dbo.MultiScoringMap", "ScoringParentId", c => c.Long(nullable: false));
            AlterColumn("dbo.MultiScoringMap", "ScoringChildId", c => c.Long(nullable: false));
            AlterColumn("dbo.Scoring_Session", "ScoringRefId", c => c.Long(nullable: false));
            AlterColumn("dbo.Scoring_Session", "SessionRefId", c => c.Long(nullable: false));
            AlterColumn("dbo.IncidentReview_LeagueMember", "ReviewRefId", c => c.Long(nullable: false));
            AlterColumn("dbo.IncidentReview_LeagueMember", "MemberRefId", c => c.Long(nullable: false));
            AddPrimaryKey("dbo.LeagueMemberEntities", "MemberId");
            AddPrimaryKey("dbo.SeasonEntities", "SeasonId");
            AddPrimaryKey("dbo.ScoringEntities", "ScoringId");
            AddPrimaryKey("dbo.SessionBaseEntities", "SessionId");
            AddPrimaryKey("dbo.ScheduleEntities", "ScheduleId");
            AddPrimaryKey("dbo.ResultEntities", "ResultId");
            AddPrimaryKey("dbo.ResultRowEntities", new[] { "ResultRowId", "ResultId" });
            AddPrimaryKey("dbo.IncidentReviewEntities", "ReviewId");
            AddPrimaryKey("dbo.ReviewCommentEntities", "CommentId");
            AddPrimaryKey("dbo.MultiScoringMap", new[] { "ScoringParentId", "ScoringChildId" });
            AddPrimaryKey("dbo.Scoring_Session", new[] { "ScoringRefId", "SessionRefId" });
            AddPrimaryKey("dbo.IncidentReview_LeagueMember", new[] { "ReviewRefId", "MemberRefId" });
            CreateIndex("dbo.SeasonEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.SeasonEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.SeasonEntities", "MainScoring_ScoringId");
            CreateIndex("dbo.ScoringEntities", "SeasonId");
            CreateIndex("dbo.ScoringEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "SeasonEntity_SeasonId");
            CreateIndex("dbo.SessionBaseEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "Schedule_ScheduleId");
            CreateIndex("dbo.ScheduleEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScheduleEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScheduleEntities", "Season_SeasonId");
            CreateIndex("dbo.ResultEntities", "ResultId");
            CreateIndex("dbo.ResultEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ResultEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ResultRowEntities", "ResultId");
            CreateIndex("dbo.ResultRowEntities", "Member_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "Author_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "MemberAtFault_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "Result_ResultId");
            CreateIndex("dbo.ReviewCommentEntities", "ReviewId");
            CreateIndex("dbo.ReviewCommentEntities", "Author_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "MemberAtFault_MemberId");
            CreateIndex("dbo.MultiScoringMap", "ScoringParentId");
            CreateIndex("dbo.MultiScoringMap", "ScoringChildId");
            CreateIndex("dbo.IncidentReview_LeagueMember", "ReviewRefId");
            CreateIndex("dbo.IncidentReview_LeagueMember", "MemberRefId");
            CreateIndex("dbo.Scoring_Session", "ScoringRefId");
            CreateIndex("dbo.Scoring_Session", "SessionRefId");
            AddForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultRowEntities", "Member_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReviewEntities", "Author_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "Author_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReview_LeagueMember", "MemberRefId", "dbo.LeagueMemberEntities", "MemberId", cascadeDelete: true);
            AddForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScoringEntities", "SeasonId", "dbo.SeasonEntities", "SeasonId", cascadeDelete: true);
            AddForeignKey("dbo.ScheduleEntities", "Season_SeasonId", "dbo.SeasonEntities", "SeasonId", cascadeDelete: true);
            AddForeignKey("dbo.ScoringEntities", "SeasonEntity_SeasonId", "dbo.SeasonEntities", "SeasonId");
            AddForeignKey("dbo.MultiScoringMap", "ScoringParentId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.MultiScoringMap", "ScoringChildId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.Scoring_Session", "ScoringRefId", "dbo.ScoringEntities", "ScoringId", cascadeDelete: true);
            AddForeignKey("dbo.SeasonEntities", "MainScoring_ScoringId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.ResultEntities", "ResultId", "dbo.SessionBaseEntities", "SessionId", cascadeDelete: true);
            AddForeignKey("dbo.Scoring_Session", "SessionRefId", "dbo.SessionBaseEntities", "SessionId", cascadeDelete: true);
            AddForeignKey("dbo.SessionBaseEntities", "Schedule_ScheduleId", "dbo.ScheduleEntities", "ScheduleId");
            AddForeignKey("dbo.ResultRowEntities", "ResultId", "dbo.ResultEntities", "ResultId", cascadeDelete: true);
            AddForeignKey("dbo.IncidentReviewEntities", "Result_ResultId", "dbo.ResultEntities", "ResultId", cascadeDelete: true);
            AddForeignKey("dbo.ReviewCommentEntities", "ReviewId", "dbo.IncidentReviewEntities", "ReviewId");
            AddForeignKey("dbo.IncidentReview_LeagueMember", "ReviewRefId", "dbo.IncidentReviewEntities", "ReviewId", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.IncidentReview_LeagueMember", "ReviewRefId", "dbo.IncidentReviewEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "ReviewId", "dbo.IncidentReviewEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "Result_ResultId", "dbo.ResultEntities");
            DropForeignKey("dbo.ResultRowEntities", "ResultId", "dbo.ResultEntities");
            DropForeignKey("dbo.SessionBaseEntities", "Schedule_ScheduleId", "dbo.ScheduleEntities");
            DropForeignKey("dbo.Scoring_Session", "SessionRefId", "dbo.SessionBaseEntities");
            DropForeignKey("dbo.ResultEntities", "ResultId", "dbo.SessionBaseEntities");
            DropForeignKey("dbo.SeasonEntities", "MainScoring_ScoringId", "dbo.ScoringEntities");
            DropForeignKey("dbo.Scoring_Session", "ScoringRefId", "dbo.ScoringEntities");
            DropForeignKey("dbo.MultiScoringMap", "ScoringChildId", "dbo.ScoringEntities");
            DropForeignKey("dbo.MultiScoringMap", "ScoringParentId", "dbo.ScoringEntities");
            DropForeignKey("dbo.ScoringEntities", "SeasonEntity_SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.ScheduleEntities", "Season_SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.ScoringEntities", "SeasonId", "dbo.SeasonEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReview_LeagueMember", "MemberRefId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ReviewCommentEntities", "Author_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.IncidentReviewEntities", "Author_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultRowEntities", "Member_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities");
            DropForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities");
            DropIndex("dbo.Scoring_Session", new[] { "SessionRefId" });
            DropIndex("dbo.Scoring_Session", new[] { "ScoringRefId" });
            DropIndex("dbo.IncidentReview_LeagueMember", new[] { "MemberRefId" });
            DropIndex("dbo.IncidentReview_LeagueMember", new[] { "ReviewRefId" });
            DropIndex("dbo.MultiScoringMap", new[] { "ScoringChildId" });
            DropIndex("dbo.MultiScoringMap", new[] { "ScoringParentId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "MemberAtFault_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "Author_MemberId" });
            DropIndex("dbo.ReviewCommentEntities", new[] { "ReviewId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "Result_ResultId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "MemberAtFault_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.IncidentReviewEntities", new[] { "Author_MemberId" });
            DropIndex("dbo.ResultRowEntities", new[] { "Member_MemberId" });
            DropIndex("dbo.ResultRowEntities", new[] { "ResultId" });
            DropIndex("dbo.ResultEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ResultEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ResultEntities", new[] { "ResultId" });
            DropIndex("dbo.ScheduleEntities", new[] { "Season_SeasonId" });
            DropIndex("dbo.ScheduleEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScheduleEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "Schedule_ScheduleId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SessionBaseEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "SeasonEntity_SeasonId" });
            DropIndex("dbo.ScoringEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "CreatedBy_MemberId" });
            DropIndex("dbo.ScoringEntities", new[] { "SeasonId" });
            DropIndex("dbo.SeasonEntities", new[] { "MainScoring_ScoringId" });
            DropIndex("dbo.SeasonEntities", new[] { "LastModifiedBy_MemberId" });
            DropIndex("dbo.SeasonEntities", new[] { "CreatedBy_MemberId" });
            DropPrimaryKey("dbo.IncidentReview_LeagueMember");
            DropPrimaryKey("dbo.Scoring_Session");
            DropPrimaryKey("dbo.MultiScoringMap");
            DropPrimaryKey("dbo.ReviewCommentEntities");
            DropPrimaryKey("dbo.IncidentReviewEntities");
            DropPrimaryKey("dbo.ResultRowEntities");
            DropPrimaryKey("dbo.ResultEntities");
            DropPrimaryKey("dbo.ScheduleEntities");
            DropPrimaryKey("dbo.SessionBaseEntities");
            DropPrimaryKey("dbo.ScoringEntities");
            DropPrimaryKey("dbo.SeasonEntities");
            DropPrimaryKey("dbo.LeagueMemberEntities");
            AlterColumn("dbo.IncidentReview_LeagueMember", "MemberRefId", c => c.Int(nullable: false));
            AlterColumn("dbo.IncidentReview_LeagueMember", "ReviewRefId", c => c.Int(nullable: false));
            AlterColumn("dbo.Scoring_Session", "SessionRefId", c => c.Int(nullable: false));
            AlterColumn("dbo.Scoring_Session", "ScoringRefId", c => c.Int(nullable: false));
            AlterColumn("dbo.MultiScoringMap", "ScoringChildId", c => c.Int(nullable: false));
            AlterColumn("dbo.MultiScoringMap", "ScoringParentId", c => c.Int(nullable: false));
            AlterColumn("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", c => c.Int());
            AlterColumn("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ReviewCommentEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ReviewCommentEntities", "Author_MemberId", c => c.Int());
            AlterColumn("dbo.ReviewCommentEntities", "ReviewId", c => c.Int());
            AlterColumn("dbo.ReviewCommentEntities", "CommentId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.IncidentReviewEntities", "Result_ResultId", c => c.Int(nullable: false));
            AlterColumn("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", c => c.Int());
            AlterColumn("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.IncidentReviewEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.IncidentReviewEntities", "Author_MemberId", c => c.Int());
            AlterColumn("dbo.IncidentReviewEntities", "ReviewId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ResultRowEntities", "Member_MemberId", c => c.Int());
            AlterColumn("dbo.ResultRowEntities", "ResultId", c => c.Int(nullable: false));
            AlterColumn("dbo.ResultRowEntities", "ResultRowId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ResultEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ResultEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ResultEntities", "ResultId", c => c.Int(nullable: false));
            AlterColumn("dbo.ScheduleEntities", "Season_SeasonId", c => c.Int(nullable: false));
            AlterColumn("dbo.ScheduleEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ScheduleEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ScheduleEntities", "ScheduleId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.SessionBaseEntities", "Schedule_ScheduleId", c => c.Int(nullable: false));
            AlterColumn("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.SessionBaseEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.SessionBaseEntities", "RaceId", c => c.Int());
            AlterColumn("dbo.SessionBaseEntities", "SessionId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ScoringEntities", "SeasonEntity_SeasonId", c => c.Int());
            AlterColumn("dbo.ScoringEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ScoringEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.ScoringEntities", "SeasonId", c => c.Int(nullable: false));
            AlterColumn("dbo.ScoringEntities", "ScoringId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.SeasonEntities", "MainScoring_ScoringId", c => c.Int());
            AlterColumn("dbo.SeasonEntities", "LastModifiedBy_MemberId", c => c.Int());
            AlterColumn("dbo.SeasonEntities", "CreatedBy_MemberId", c => c.Int());
            AlterColumn("dbo.SeasonEntities", "SeasonId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.LeagueMemberEntities", "MemberId", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.IncidentReview_LeagueMember", new[] { "ReviewRefId", "MemberRefId" });
            AddPrimaryKey("dbo.Scoring_Session", new[] { "ScoringRefId", "SessionRefId" });
            AddPrimaryKey("dbo.MultiScoringMap", new[] { "ScoringParentId", "ScoringChildId" });
            AddPrimaryKey("dbo.ReviewCommentEntities", "CommentId");
            AddPrimaryKey("dbo.IncidentReviewEntities", "ReviewId");
            AddPrimaryKey("dbo.ResultRowEntities", new[] { "ResultRowId", "ResultId" });
            AddPrimaryKey("dbo.ResultEntities", "ResultId");
            AddPrimaryKey("dbo.ScheduleEntities", "ScheduleId");
            AddPrimaryKey("dbo.SessionBaseEntities", "SessionId");
            AddPrimaryKey("dbo.ScoringEntities", "ScoringId");
            AddPrimaryKey("dbo.SeasonEntities", "SeasonId");
            AddPrimaryKey("dbo.LeagueMemberEntities", "MemberId");
            CreateIndex("dbo.Scoring_Session", "SessionRefId");
            CreateIndex("dbo.Scoring_Session", "ScoringRefId");
            CreateIndex("dbo.IncidentReview_LeagueMember", "MemberRefId");
            CreateIndex("dbo.IncidentReview_LeagueMember", "ReviewRefId");
            CreateIndex("dbo.MultiScoringMap", "ScoringChildId");
            CreateIndex("dbo.MultiScoringMap", "ScoringParentId");
            CreateIndex("dbo.ReviewCommentEntities", "MemberAtFault_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "Author_MemberId");
            CreateIndex("dbo.ReviewCommentEntities", "ReviewId");
            CreateIndex("dbo.IncidentReviewEntities", "Result_ResultId");
            CreateIndex("dbo.IncidentReviewEntities", "MemberAtFault_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.IncidentReviewEntities", "Author_MemberId");
            CreateIndex("dbo.ResultRowEntities", "Member_MemberId");
            CreateIndex("dbo.ResultRowEntities", "ResultId");
            CreateIndex("dbo.ResultEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ResultEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ResultEntities", "ResultId");
            CreateIndex("dbo.ScheduleEntities", "Season_SeasonId");
            CreateIndex("dbo.ScheduleEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScheduleEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "Schedule_ScheduleId");
            CreateIndex("dbo.SessionBaseEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.SessionBaseEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "SeasonEntity_SeasonId");
            CreateIndex("dbo.ScoringEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "CreatedBy_MemberId");
            CreateIndex("dbo.ScoringEntities", "SeasonId");
            CreateIndex("dbo.SeasonEntities", "MainScoring_ScoringId");
            CreateIndex("dbo.SeasonEntities", "LastModifiedBy_MemberId");
            CreateIndex("dbo.SeasonEntities", "CreatedBy_MemberId");
            AddForeignKey("dbo.IncidentReview_LeagueMember", "ReviewRefId", "dbo.IncidentReviewEntities", "ReviewId", cascadeDelete: true);
            AddForeignKey("dbo.ReviewCommentEntities", "ReviewId", "dbo.IncidentReviewEntities", "ReviewId");
            AddForeignKey("dbo.IncidentReviewEntities", "Result_ResultId", "dbo.ResultEntities", "ResultId", cascadeDelete: true);
            AddForeignKey("dbo.ResultRowEntities", "ResultId", "dbo.ResultEntities", "ResultId", cascadeDelete: true);
            AddForeignKey("dbo.SessionBaseEntities", "Schedule_ScheduleId", "dbo.ScheduleEntities", "ScheduleId", cascadeDelete: true);
            AddForeignKey("dbo.Scoring_Session", "SessionRefId", "dbo.SessionBaseEntities", "SessionId", cascadeDelete: true);
            AddForeignKey("dbo.ResultEntities", "ResultId", "dbo.SessionBaseEntities", "SessionId", cascadeDelete: true);
            AddForeignKey("dbo.SeasonEntities", "MainScoring_ScoringId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.Scoring_Session", "ScoringRefId", "dbo.ScoringEntities", "ScoringId", cascadeDelete: true);
            AddForeignKey("dbo.MultiScoringMap", "ScoringChildId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.MultiScoringMap", "ScoringParentId", "dbo.ScoringEntities", "ScoringId");
            AddForeignKey("dbo.ScoringEntities", "SeasonEntity_SeasonId", "dbo.SeasonEntities", "SeasonId");
            AddForeignKey("dbo.ScheduleEntities", "Season_SeasonId", "dbo.SeasonEntities", "SeasonId", cascadeDelete: true);
            AddForeignKey("dbo.ScoringEntities", "SeasonId", "dbo.SeasonEntities", "SeasonId", cascadeDelete: true);
            AddForeignKey("dbo.IncidentReviewEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReviewEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReview_LeagueMember", "MemberRefId", "dbo.LeagueMemberEntities", "MemberId", cascadeDelete: true);
            AddForeignKey("dbo.IncidentReviewEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "MemberAtFault_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ReviewCommentEntities", "Author_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.IncidentReviewEntities", "Author_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultRowEntities", "Member_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ResultEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScheduleEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScheduleEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SessionBaseEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SessionBaseEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScoringEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.ScoringEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SeasonEntities", "LastModifiedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
            AddForeignKey("dbo.SeasonEntities", "CreatedBy_MemberId", "dbo.LeagueMemberEntities", "MemberId");
        }
    }
}
